{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}

-- | persistent on Cloudflare D1.
--
-- @
-- db <- D1.d1 env \"DB\"
-- runD1 db $ selectList [UserName ==. \"ann\"] []
-- @
--
-- SQL is generated by persistent-sqlite's SQLite dialect and executed with
-- "Cloudflare.Workers.D1". Differences from persistent-sqlite:
--
-- * __No transactions.__ D1 has no BEGIN\/COMMIT, so each statement commits
--   on its own and an exception does not undo earlier writes. Use
--   'Cloudflare.Workers.D1.batch' for writes that must be atomic.
-- * __At most 100 parameters per statement__ (D1's limit). @insertMany_@ and
--   @insertEntityMany@ are split into chunks; @putMany@ and @repsertMany@ run
--   row by row. A single statement with more than 100 parameters (a @<-.@
--   filter or @getMany@ over many keys, say) fails.
-- * __Values.__ Binding converts values as persistent-sqlite does, but D1
--   stores and returns them differently (see "Cloudflare.Workers.D1"):
--   numbers are bound as REAL, so an @Int@ written to a TEXT column is stored
--   as @\"5.0\"@; a whole-number REAL reads back as 'PersistInt64', which the
--   built-in instances accept but a custom 'PersistField' expecting
--   'PersistDouble' may not; integers and keys outside ±(2^53 − 1) throw
--   'Cloudflare.Workers.D1.D1Exception'.
-- * __Queries are not streamed.__ D1 returns all rows at once, and
--   @selectSource@ yields them from memory.
-- * __SQL is not logged__: @connLogFunc@ does nothing.
-- * __Migrations are not run here.__ 'd1MigrationSql' returns the statements;
--   apply them with @wrangler d1 migrations@.
module Database.Persist.D1
  ( d1Backend
  , runD1
  , createD1Pool
  , d1MigrationSql
  ) where

import qualified Cloudflare.Workers.D1        as D1
import           Control.Monad.IO.Class       (MonadIO, liftIO)
import           Control.Monad.Trans.Reader   (runReaderT)
import           Data.Acquire                 (Acquire)
import           Data.Conduit                 (ConduitM, yield)
import           Data.Fixed                   (Pico)
import           Data.IORef                   (newIORef)
import           Data.Pool                    (Pool, defaultPoolConfig, newPool)
import           Data.Text                    (Text)
import qualified Data.Text                    as T
import qualified Data.Text.Encoding           as TE
import qualified Data.Text.Encoding.Error     as TEE
import           Database.Persist.Sql
import           Database.Persist.SqlBackend
import           Database.Persist.Sqlite      (escape, insertSql', migrate')
import           Database.Sqlite              (format8601)

-- | A 'SqlBackend' for this database. Cheap: build one per request if
-- convenient.
d1Backend :: D1.D1Database -> IO SqlBackend
d1Backend db = do
  smap <- newIORef mempty
  pure $
    -- No setConnPutManySql / setConnRepsertManySql: those build one statement
    -- for all rows, which D1's parameter limit rejects; persistent's default
    -- runs them row by row instead.
    setConnMaxParams 100 $
      mkSqlBackend
        MkSqlBackendArgs
          { connPrepare = prepareD1 db
          , connStmtMap = smap
          , connInsertSql = insertReturning
          , connClose = pure ()
          , connMigrateSql = migrate'
          , connBegin = \_ _ -> pure ()
          , connCommit = \_ -> pure ()
          , connRollback = \_ -> pure ()
          , connEscapeFieldName = escape . unFieldNameDB
          , connEscapeTableName = escape . unEntityNameDB . getEntityDBName
          , connEscapeRawName = escape
          , connNoLimit = "LIMIT -1"
          , connRDBMS = "sqlite"
          , connLimitOffset = decorateSQLWithLimitOffset "LIMIT -1"
          , connLogFunc = \_ _ _ _ -> pure ()
          }

-- | persistent-sqlite fetches the new id with a second statement that reads
-- @last_insert_rowid()@. On Workers, requests interleave within an isolate,
-- so that can return another request's id; RETURNING gets it in the same
-- statement.
insertReturning :: EntityDef -> [PersistValue] -> InsertSqlResult
insertReturning ent vals =
  case (insertSql' ent vals, getEntityId ent) of
    (ISRInsertGet ins _, EntityIdField fd) ->
      ISRSingle (ins <> " RETURNING " <> escape (unFieldNameDB (fieldDB fd)))
    (other, _) -> other

-- | Run persistent actions against this database.
runD1 :: D1.D1Database -> SqlPersistT IO a -> IO a
runD1 db action = d1Backend db >>= runReaderT action

-- | A pool for 'runSqlPool' (and Yesod's runDB). Backends are cheap and hold
-- no connection; the pool exists so code written for a pool works unchanged.
createD1Pool :: D1.D1Database -> IO (Pool SqlBackend)
-- The pool's size and idle time are arbitrary: a pooled backend holds no
-- connection, so neither limits anything.
createD1Pool db = newPool (defaultPoolConfig (d1Backend db) (\_ -> pure ()) 60 10)

-- | The statements persistent would run to migrate this database to the
-- given definitions. Nothing is executed.
--
-- To change a table, persistent-sqlite copies it into a backup table, drops
-- and recreates it, and copies the rows back. It makes the backup a TEMP
-- table, which D1 refuses (@not authorized@), so here the backup is an
-- ordinary table; the migration drops it at the end.
d1MigrationSql :: D1.D1Database -> Migration -> IO [Text]
d1MigrationSql db migration = map noTemp <$> runD1 db (getMigration migration)
  where
    noTemp s = maybe s ("CREATE TABLE " <>) (T.stripPrefix "CREATE TEMP TABLE " s)

prepareD1 :: D1.D1Database -> Text -> IO Statement
prepareD1 db sql =
  pure
    Statement
      { stmtFinalize = pure ()
      , stmtReset = pure ()
      , stmtExecute = \vals -> D1.changes <$> D1.execute db (D1.Statement sql (map toD1 vals))
      , stmtQuery = queryD1 db sql
      }

queryD1 :: (MonadIO m) => D1.D1Database -> Text -> [PersistValue] -> Acquire (ConduitM () [PersistValue] m ())
-- The statement runs when the query is acquired, not when the rows are
-- pulled: persistent's insert_ acquires an INSERT … RETURNING and never
-- reads it.
queryD1 db sql vals = do
  result <- liftIO (D1.query db (D1.Statement sql (map toD1 vals)))
  pure (mapM_ (yield . map fromD1) (D1.rows result))

-- | Converts as persistent-sqlite's Database.Sqlite.bind does. The stored
-- values can still differ, since D1 binds every number as a REAL.
toD1 :: PersistValue -> D1.D1Value
toD1 = \case
  PersistInt64 n -> D1.D1Integer n
  PersistDouble x -> D1.D1Real x
  PersistRational r -> D1.D1Text (T.pack (show (fromRational r :: Pico)))
  PersistBool b -> D1.D1Integer (if b then 1 else 0)
  PersistText t -> D1.D1Text t
  PersistByteString b -> D1.D1Blob b
  PersistNull -> D1.D1Null
  PersistDay d -> D1.D1Text (T.pack (show d))
  PersistTimeOfDay t -> D1.D1Text (T.pack (show t))
  PersistUTCTime t -> D1.D1Text (T.pack (format8601 t))
  PersistList l -> D1.D1Text (listToJSON l)
  PersistMap m -> D1.D1Text (mapToJSON m)
  PersistArray a -> D1.D1Text (listToJSON a)
  PersistObjectId _ -> error "persistent-d1: refusing to serialize a PersistObjectId"
  PersistLiteral_ _ s -> D1.D1Text (TE.decodeUtf8With TEE.lenientDecode s)

fromD1 :: D1.D1Value -> PersistValue
fromD1 = \case
  D1.D1Null -> PersistNull
  D1.D1Integer n -> PersistInt64 n
  D1.D1Real x -> PersistDouble x
  D1.D1Text t -> PersistText t
  D1.D1Blob b -> PersistByteString b
