{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE ViewPatterns #-}

-- | The Stage 2 demo: a minimal Yesod application on the same handler.
--
-- Nothing here is Workers-specific except the @foreign export@ line and the
-- use of 'runCloudflare' in place of @warp@. The routing, the type-safe URLs
-- and the Hamlet template are ordinary Yesod, generated by Template Haskell --
-- which is why the toolchain is pinned to GHC 9.12, the first release whose
-- wasm backend can run TH splices.
module Main (main) where

import           Data.Text                      (Text)
import           Network.Wai.Handler.Cloudflare (runCloudflare)
import           Yesod.Core

data App = App

mkYesod "App" [parseRoutes|
/          HomeR  GET
/hello/#Text  HelloR GET
|]

instance Yesod App where
  -- The default uses clientsession to sign cookies, which needs entropy the
  -- Workers sandbox does not offer through WASI. This PoC serves no sessions.
  makeSessionBackend _ = pure Nothing

getHomeR :: Handler Html
getHomeR = defaultLayout $ do
  setTitle "workers-wai"
  [whamlet|
    <h1>Hello from Yesod on Cloudflare Workers
    <p>
      This page was rendered by Yesod, compiled to WebAssembly by GHC, running
      inside the Workers runtime.
    <p>
      <a href=@{HelloR "world"}>Try a type-safe route
  |]

getHelloR :: Text -> Handler Html
getHelloR name = defaultLayout $ do
  setTitle "workers-wai"
  [whamlet|
    <h1>Hello, #{name}!
    <p>
      <a href=@{HomeR}>Back
  |]

foreign export javascript "workerMain" main :: IO ()

main :: IO ()
main = do
  app <- toWaiAppPlain App
  runCloudflare app
